name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        
      - name: Installation des dépendances
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make
          
      - name: Compilation du projet
        run: make
        
      - name: Exécution des tests
        run: make test
        
      - name: Nettoyage
        run: make clean